- package.json
- pnpm-lock.yaml
- src/app/App.tsx
- src/app/routers/app-router.tsx
- src/app/routers/index.ts
- src/pages/home/index.ts
- src/pages/home/ui/home-page.tsx
> feat: react-router 설정

- package.json
- pnpm-lock.yaml
- src/app/App.tsx
- src/app/providers/index.ts
- src/app/providers/providers.tsx
URL search params를 쉽게 파싱하기 위해 nuqs 라이브러리를 추가하였습니다.
https://nuqs.47ng.com/
> feat: nuqs 세팅

- src/app/routers/app-router.tsx
- src/shared/ui/layout.tsx
> feat: 홈페이지 레이아웃 생성

- src/app/routers/app-router.tsx
- src/pages/auth/index.ts
- src/pages/auth/ui/auth-page.tsx
- src/pages/login/index.ts
- src/pages/login/ui/login-page.tsx
- src/shared/ui/index.ts
로그인 페이지 생성을 진행하였습니다.
현재 카카오 로그인만 테스트 진행.
> feat: 로그인페이지 생성

- src/pages/login/ui/login-page.tsx
배포된 환경에서도 redirect uri가 올바르게 작동할 수 있도록 변경하였습니다.
> feat: redirect uri 도메인에 따라서 변경

- .prettierrc
- package.json
- pnpm-lock.yaml
- src/pages/login/ui/login-page.tsx
- src/shared/ui/layout.tsx
className 정렬을 위해 prettier plugin tailwindcss 를 적용하였습니다.
> style: prettier-plugin-tailwindcss 적용

- package.json
- pnpm-lock.yaml
- src/shared/api/http-client.ts
- src/shared/api/index.ts
> feat: axios 설정

- .dockerignore
- Dockerfile
> feat: Dockerfile 추가

- package.json
- pnpm-lock.yaml
- src/app/routers/app-router.tsx
- src/pages/help/index.ts
- src/pages/help/ui/help-page.tsx
- src/pages/help/ui/tab.tsx
- src/pages/help/ui/topic.tsx
- src/shared/lib/utils.ts
- src/shared/ui/layout.tsx
> feat: 공지사항, FAQ 마크업

- dev.Dockerfile
> fix: 도커파일 임시 변경

- dev.Dockerfile
corepack 0.31 버전 출시로 인한 이슈
- https://vercel.com/guides/corepack-errors-github-actions
- https://github.com/nodejs/corepack/releases
> fix: corepack 업데이트

- package.json
- pnpm-lock.yaml
- src/app/providers/providers.tsx
> chore: tanstack query 추가

- src/app/routers/app-router.tsx
- src/pages/stock-list/index.ts
- src/pages/stock-list/ui/stock-list-page.tsx
- /pages/stock-list/ 디렉토리 생성
- 주식 목록 페이지 기본 컴포넌트 구조 설정
- router 추가
> feat: 주식 목록 페이지 구조 추가

- src/pages/help/api/query.ts
- src/pages/help/ui/announcement-list.tsx
- src/pages/help/ui/help-page.tsx
> feat: 공지사항 페이징 구현

- .env.production
> feat: production 환경변수 설정

- src/pages/help/api/get-announcements.ts
- src/pages/help/ui/announcement-list.tsx
pagenation > pagination 필드명 변경
> fix: pagination schema 필드명 변경

- src/app/routers/app-router.tsx
- src/pages/stock-detail/index.ts
- src/pages/stock-detail/ui/stock-detail-page.tsx
- src/pages/stock-list/ui/stock-list-page.tsx
> feat: 주식 상세 페이지 구조 추가

- src/app/routers/app-router.tsx
- src/pages/news/index.ts
- src/pages/news/ui/news-page.tsx
- src/shared/ui/layout.tsx
> feat: 뉴스페이지 마크업

- src/pages/home/ui/ai-recommend-section.tsx
- src/pages/home/ui/home-page.tsx
> feat: 홈화면 AI 추천 종목 섹션 마크업

- src/pages/home/ui/ai-recommend-section.tsx
> feat: tradingview iframe 연동

- src/pages/stock-detail/ui/stock-detail-page.tsx
- src/pages/stock-detail/ui/stock-header.tsx
> feat: 주식 헤더 마크업

- src/entities/faq/api/schema.ts
- src/pages/help/ui/faq-list.tsx
faq 리스트 api의 모델이 백엔드측에서 변경되어 이에따라 변경하였습니다.
> feat: faq 리스트 api model 변경

- prod.Dockerfile
- src/app/providers/providers.tsx
- src/app/providers/user-provider.tsx
- src/pages/auth/api/kakao-login.ts
- src/pages/auth/ui/auth-page.tsx
- src/shared/api/get-current-user.ts
- src/shared/api/http-client.ts
- src/shared/api/query.ts
- src/shared/api/schema.ts
- src/shared/ui/layout.tsx
- vite.config.ts
> feat: 카카오로그인 연동

- src/app/routers/app-router.tsx
- src/pages/help/ui/help-page.tsx
- src/pages/my/index.ts
- src/pages/my/ui/my-page.tsx
- src/shared/ui/index.ts
- src/shared/ui/layout.tsx
- src/shared/ui/tab.tsx
마이페이지 생성 및 탭 컴포넌트를 shared로 분리하였습니다.
> feat: 마이페이지 생성 및 탭 컴포넌트 공통화

- src/pages/my/ui/my-page.tsx
> feat: 회원정보수정 페이지 마크업

- src/pages/home/ui/home-page.tsx
- src/pages/home/ui/news-section.tsx
> feat: 홈 화면 뉴스 섹션 생성

- src/app/routers/app-router.tsx
- src/pages/favorite-stocks/index.ts
- src/pages/favorite-stocks/ui/favorite-stocks-page.tsx
> feat: 내 관심종목 마크업

- src/entities/stock/api/get-stock.ts
- src/entities/stock/api/query.ts
- src/pages/stock-detail/ui/stock-analysis-table.tsx
- src/pages/stock-detail/ui/stock-analyst.tsx
- 주식 상세 정보 API 연동 (가격, 상세 정보)
- 쿼리 키 구조 개선으로 캐싱 최적화 (detail, price, summary 각각 고유한 키 사용)
- 주식 분석 테이블 UI 개선 및 툴팁 텍스트 개선
- 20240101 ~ 20241231 날짜 조정으로 24년 배당금 조회
> feat: 주식 상세 정보 API 연동

- src/pages/stock-detail/api/get-financial-data.ts
- src/pages/stock-detail/api/query.ts
- src/pages/stock-detail/api/schema.ts
- src/pages/stock-detail/ui/financial-table.tsx
- src/pages/stock-detail/ui/stock-analyst.tsx
- 재무 비율 API 연동
- 분기별로 고정 (fidDivClsCode: '1')
- 기존 하드코딩된 샘플 데이터 제거
- 데이터 로딩 상태 처리를 위한 Suspense 적용
> feat: 재무지표 API 연동

- src/entities/stock/api/get-investor-opinions.ts
- src/entities/stock/api/query.ts
- src/entities/stock/api/schema.ts
- src/pages/stock-detail/ui/date.ts
- src/pages/stock-detail/ui/investor-opinion-chart.tsx
- src/pages/stock-detail/ui/investor-opinion-table.tsx
- src/pages/stock-detail/ui/stock-analyst.tsx
- src/pages/stock-detail/ui/utill.ts
- 투자사별 의견(종목 투자 의견) API 연동
- 투자사별 의견 테이블 및 차트 데이터를 실제 API 응답으로 변경
- 날짜 포맷팅 및 투자 의견 코드 변환 유틸리티 함수 추가
> feat: 투자사별 의견 API 연동

- src/pages/stock-detail/api/delete-comment.ts
- src/pages/stock-detail/api/get-comment-replies.ts
- src/pages/stock-detail/api/query.ts
- src/pages/stock-detail/ui/comment-base.tsx
- src/pages/stock-detail/ui/comment-item.tsx
- src/pages/stock-detail/ui/community.tsx
- 사용자 정보 가져오기 구현
- 댓글/대댓글 삭제 API 연동
- 대댓글 쿼리 구조 변경
> feat: 댓글 삭제 API 연동

- src/pages/home/api/get-stock-ranks.ts
- src/pages/home/api/query.ts
- src/pages/home/api/schema.ts
- src/pages/home/ui/ranking-section.tsx
- 급등주, 주식 TOP5 순위 API 연동
- 주요 시장 정보는 API가 존재 X
> feat: 홈화면 랭크 순위 API 연동

- src/pages/stock-detail/api/get-comment-replies.ts
- src/pages/stock-detail/api/get-comments.ts
- src/pages/stock-detail/api/post-comment-like.ts
- src/pages/stock-detail/api/query.ts
- src/pages/stock-detail/api/schema.ts
- src/pages/stock-detail/ui/comment-base.tsx
- src/pages/stock-detail/ui/comment-item.tsx
- src/pages/stock-detail/ui/comment-menu.tsx
- src/pages/stock-detail/ui/community.tsx
- 커뮤니티 댓글/대댓글 좋아요 API 연동
- 댓글 정렬 적용 (댓글 조회 API 변경으로 업데이트)
- 대댓글 영역 스크롤 제거 및 
- 메뉴 클릭 시 메뉴 창(floating UI)이 정상적으로 위치하지 않는 문제 발생
- 대댓글 영역 밖으로 floating이 안됨(대댓글 영역의 스크롤이 늘어남)
- max-height + auto scrolling이 영향을 미치는 것을 확인 후 제거
- 댓글 메뉴 창 외부 클릭 닫힘 처리
> feat: 커뮤니티 댓글 좋아요 API 연동

- vercel.json
> chore: vercel 파일 설정

- src/pages/stock-detail/ui/stock-analyst.tsx
- src/pages/stock-detail/ui/stock-detail-page.tsx
- src/pages/stock-detail/ui/stock-header.tsx
- 상세 페이지 관심 종목 조회 수정
- 비로그인 시에도 관심종목을 조회하는 불필요한 로직 존재
- user가 존재할때만 조회하도록 수정
- 주식 상세 페이지 스켈레톤 추가
- 주식 상세 페이지의 로딩 지연으로 스켈레톤 추가
> fix: 상세 페이지 관심 종목 조회 수정 및 스켈레톤 추가
